#!/usr/bin/env bash
#

set -o nounset \
    -o errexit


# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "===> Building ..."
npm run build --production

echo "===> Running ... "
exec node server.js